### ISSUE TITLE
Exception: requested device index 0, but found 0 devices

### ISSUE THREAD

**Issue by Zhangkaiwen2001** [JeffreyXiang/ivid#11]
Traceback (most recent call last):
  File "/data/zhangkaiwen/ivid-main/inference/sample.py", line 342, in <module>
    main(0, 1, seeds, modelviews, classes, cfg, cfg_uncond, cfg_cond)
  File "/data/zhangkaiwen/ivid-main/inference/sample.py", line 223, in main
    for i, (meshes, colors, samples, conds) in enumerate(sample_process):
  File "/data/zhangkaiwen/anaconda3/envs/I2V_attack/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/data/zhangkaiwen/ivid-main/inference/sample.py", line 50, in sample_all
    renderer = [rgbd_3d.AggregationRenderer(128 * 3, 128) for _ in range(batchsize)]
  File "/data/zhangkaiwen/ivid-main/inference/sample.py", line 50, in <listcomp>
    renderer = [rgbd_3d.AggregationRenderer(128 * 3, 128) for _ in range(batchsize)]
  File "/data/zhangkaiwen/ivid-main/rgbd_3d/moderngl_renderer.py", line 169, in __init__
    self.init_gl_context(device)
  File "/data/zhangkaiwen/ivid-main/rgbd_3d/moderngl_renderer.py", line 177, in init_gl_context
    self.mgl_ctx = moderngl.create_context(standalone=True, backend='egl', device_index=device)
  File "/data/zhangkaiwen/anaconda3/envs/I2V_attack/lib/python3.9/site-packages/moderngl/__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/data/zhangkaiwen/anaconda3/envs/I2V_attack/lib/python3.9/site-packages/glcontext/__init__.py", line 120, in create
    return egl.create_context(**kwargs)
Exception: requested device index 0, but found 0 devices
Exception ignored in: <function AggregationRenderer.__del__ at 0x7f370ed44280>
Traceback (most recent call last):
  File "/data/zhangkaiwen/ivid-main/rgbd_3d/moderngl_renderer.py", line 246, in __del__
    self.mgl_ctx.release()
AttributeError: 'NoneType' object has no attribute 'release'

can you tell me what should i do?

**Comment by Zhangkaiwen2001** [comment]
command: CUDA_VISIBLE_DEVICES=2 python inference/sample.py --num_samples 10000 --classes uniform --viewset 3x9 --steps_uncond 1000 --steps_cond 50 --guidance 0.5

**Comment by ewrfcas** [comment]
Some GPUs are not supported.
